name: whatsapp_bot_platform_interface
description: Whatsapp bot platform interface
version: 1.0.4
homepage: https://github.com/rohitsangwan01/whatsapp_bot_flutter
repository: https://github.com/rohitsangwan01/whatsapp_bot_flutter
issue_tracker: https://github.com/rohitsangwan01/whatsapp_bot_flutter/issues

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  http: ^1.2.1
  zxing2: ^0.2.3
  mime: ^1.0.5

dev_dependencies:
  lints: ^2.0.1
