name: whatsapp_bot
description: A new Flutter plugin project.
version: 0.0.1
homepage:

environment:
  sdk: ">=2.18.2 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  puppeteer: ^2.14.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  
# Desktop Only
# flutter:
#   plugin:
#     platforms:
#       macos:
#         pluginClass: WhatsappBotPlugin
