name: whatsapp_bot_flutter
description: Whatsapp bot using puppeteer and whatsapp web scraping with flutter desktop/web and dart projects support
version: 0.0.8
homepage: https://github.com/rohitsangwan01/whatsapp_bot_flutter
repository: https://github.com/rohitsangwan01/whatsapp_bot_flutter
issue_tracker: https://github.com/rohitsangwan01/whatsapp_bot_flutter/issues

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  zxing2: ^0.1.1
  http: ^0.13.5
  puppeteer: ^2.17.0
  flutter_inappwebview: ^6.0.0-beta.12

dev_dependencies:
  lints: ^2.0.1
