name: whatsapp_bot_flutter
description: Whatsapp bot using whatsapp web scrapping
version: 0.0.1
homepage: https://github.com/rohitsangwan01/whatsapp_bot_flutter

environment:
  sdk: ">=2.18.2 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  puppeteer: ^2.14.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
# TODO : Add platforms
