name: whatsapp_bot_flutter
description: Whatsapp bot using whatsapp web scraping
version: 0.0.4
homepage: https://github.com/rohitsangwan01/whatsapp_bot_flutter

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  zxing2: ^0.1.1
  puppeteer: ^2.14.0

dev_dependencies:
  flutter_lints: ^2.0.0

flutter:
